sudo: False

language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    # added power support arch.
    - python: 3.6
      arch: ppc64le   
    - python: 3.7
      arch: ppc64le
    - python: 3.8
      arch: ppc64le
install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test -c conda-forge python=$TRAVIS_PYTHON_VERSION pytest flake8 black heapdict
  - source activate test
  - conda install -c conda-forge python-lmdb psutil

  - python setup.py install

script:
  - py.test --doctest-modules zict
  - flake8 zict
  - black --check zict

notifications:
  email: false
